address: 0.0.0.0:888
log:
  output-path: "/var/log/achilles/access.log"
  max-time: 14
  rotate-time: 1
datasource:
  msyql: "root:password@tcp(127.0.0.1:3306)/test?charset=utf8"
target:
  endpoint: "127.0.0.1:1235"
